name: Feedback Analytics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'

jobs:
  feedback-analytics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run feedback analytics
        run: |
          python scripts/feedback_analytics.py
      - name: Upload feedback log artifact
        uses: actions/upload-artifact@v4
        with:
          name: feedback_analytics_log
          path: feedback_analytics.log
